name: WebApp Deployment
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Upload production build
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: dist

  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Download production build
        uses: actions/download-artifact@v3
        with:
          name: release
          path: dist

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_COOKING_D8911 }}
          projectId: cooking-d8911
